### PR TITLE
Assign directly deep into BenchmarkGroup

### LINKED ISSUE #101: Assign deep into BenchmarkGroup using vector key
It would be nice if one could assign directly deep into a `BenchmarkGroup` using
a `Vector` key. The intermediate groups should be created automatically as
necessary. Currently:

    julia>  using BenchmarkTools
    julia>  g = BenchmarkGroup()
    julia>  g[[1, "a", :b]] = "hello"
    ERROR: KeyError: key 1 not found

One would have to do

    julia>  using BenchmarkTools
    julia>  g = BenchmarkGroup(1 => BenchmarkGroup("a" => BenchmarkGroup()))
    julia>  g[[1, "a", :b]] = "hello"
    "hello"

Expected:

    julia>  using BenchmarkTools
    julia>  g = BenchmarkGroup()
    julia>  g[[1, "a", :b]] = "hello"
    "hello"

### PR DESCRIPTION
**Pull request by goerz**
This allows to assign directly deep into a BenchmarkGroup with a Vector
key, creating all intermediate levels as necessary:

    julia>  using BenchmarkTools
    julia>  g = BenchmarkGroup()
    julia>  g[[1, "a", :b]] = "hello"
    "hello"

Closes #101

### CODE REVIEW

**Comment by goerz** [comment]
For some reason I can't test this locally (before or after my commit):

    julia>  Pkg.test("BenchmarkTools")
    INFO: Testing BenchmarkTools
    Testing Parameters...done (took 0.476795949 seconds)
    Testing Trial/TrialEstimate/TrialRatio/TrialJudgement...done (took 1.523126521 seconds)
    Testing BenchmarkGroup...WARNING: import of BenchmarkTools.Parameters into Main conflicts with an existing identifier; ignored.
    ERROR: LoadError: LoadError: function Module does not accept keyword arguments
    Stacktrace:
    [1] kwfunc(::Any) at ./boot.jl:237
    [2] include_from_node1(::String) at ./loading.jl:576
    [3] include(::String) at ./sysimg.jl:14
    [4] include_from_node1(::String) at ./loading.jl:576
    [5] include(::String) at ./sysimg.jl:14
    [6] process_options(::Base.JLOptions) at ./client.jl:305
    [7] _start() at ./client.jl:371
    while loading /home/goerz/.julia/v0.6/BenchmarkTools/test/GroupsTests.jl, in expression starting on line 19
    while loading /home/goerz/.julia/v0.6/BenchmarkTools/test/runtests.jl, in expression starting on line 293
    =========================================================================================[ ERROR: BenchmarkTools ]==========================================================================================

    failed process: Process(`/data/goerz/julia/bin/julia -Cnative -J/data/goerz/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/goerz/.julia/v0.6/BenchmarkTools/test/runtests.jl`, ProcessExited(1)) [1]

    ============================================================================================================================================================================================================
    ERROR: BenchmarkTools had test errors

Any idea what is wrong here?

**Comment by goerz** [comment]
Since CI seems to go through: let me add a test before this is ready to merge...

**Comment by goerz** [comment]
I should add that it *does* work in my actual usage, it was just a problem of running the test suite. As far as I'm concerned, there isn't anything that should block this to be merged

File: test/GroupsTests.jl [hunk 1]
```diff
@@ -235,4 +235,18 @@ gx["e"] = BenchmarkGroup([], "1" => g["e"]["1"][x["a"]], "3" => g["e"]["3"][x["c
 
 @test g[x] == gx
 
+# deep index assignment in BenchmarkGroup #
+#-----------------------------------------#
```
Comment (jrevels) [inline test/GroupsTests.jl]: Maybe change this heading to `indexing by Vector` to match the other headers (which in turn match the headers in the manual)

**Comment by jrevels** [comment]
Sorry for the late reply, I must've missed the notification for this PR! LGTM feature-wise. 

Can you add a description/example of this to the [relevant section of the manual](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#indexing-into-a-benchmarkgroup-using-a-vector)?

> Any idea what is wrong here?

Just a shot in the dark, but was the [the Parameters package](https://github.com/mauro3/Parameters.jl) somehow loaded into the test namespace? Something like that could cause the error message you were seeing.

**Comment by goerz** [comment]
Okay, I changed the heading and added a paragraph to the manual

**Comment by jrevels** [comment]
Thanks!
